Close #24
TangutCorpus/TangutSite pull request #44
Opened 2024-09-30 16:07 UTC by witbore

Move files from the plugin directory as part of the implementation of a three layer architecture.

2024-10-01 08:41 UTC, LeonovDS requested changes
И по структуре папок в целом:
- domain - это другое название service слоя. Т.е. место, где происходит основная бизнес-логика
- Репозиторий обычно хранится одним из двух путей: либо все в одном модуле, либо интерфейс в сервисном слое, а имплементация в доменном, чтобы зависимости имели правильное направление
- Папку конфиг можно поднять в корень и избавиться от infrastructure
- web/routes = presentation, но можно оставить и routes (а делать просто так вложеные модули имхо излишне)

Итого должна получиться примерно такая структура:
- repository
  - Repo
  - RepoImpl 
- domain/service
  - UserService - если все-таки хочешь оставить интерфейс
  - UserServiceImpl
- routes/presentation
  - Здесь все связанное с ручками 
- model
- config 

Предлагаю просмотреть остальные комментарии, но не тратить время на их исправление, быстро перекидать папки, поменять имя корневого пакета (а то почему-то оказалось com.example, хотя помню, что при генерации проекта проставлял другое) и приступать к работе с бд, чтобы уже тренироваться не с заглушками, а с реальным кодом

2024-10-01 08:41 UTC, LeonovDS commented on backend/src/main/kotlin/com/example/domain/model/ExposedUser.kt
> +data class ExposedUser(val name: String, val age: Int)
Нужны новые строки на конце файлов. Позже настрою автоматику

2024-10-01 08:41 UTC, LeonovDS commented on backend/src/main/kotlin/com/example/domain/service/UserService.kt
> +interface UserService {
Избыточно. Интерфейс здесь не особо нужен. Плюс выходит почти полный дубликат репозитория. Лучше, когда уже будут понятны ручки, сделать методы в сервисе +- соответствующие им

2024-10-01 08:41 UTC, LeonovDS commented on backend/src/main/kotlin/com/example/infrastructure/config/Security.kt
> +                JWT.require(Algorithm.HMAC256(jwtSecret)).withAudience(jwtAudience)
Имхо, как было более читаемо, но скорее всего это был автоформат. Опять же постараюсь настроить

2024-10-01 08:41 UTC, LeonovDS commented on backend/src/main/kotlin/com/example/infrastructure/database/UserRepositoryImpl.kt
> +package com.example.infrastructure.database
Точно не в infrastructure

2024-10-01 08:41 UTC, LeonovDS commented on backend/src/main/kotlin/com/example/web/routes/Routing.kt
> +        var userService = UserServiceImpl(userRepository)
Это в целом не должно быть в routing, так как основная задача здесь - показать ручки. Пока можно оставить. Потом затащим в проект di и перепишем нормально

2024-10-01 10:28 UTC, witbore commented
Моя логика была такой:
- web — обработка входящих запросов, например, маршрутизация и контроллеры.
- domain — логика приложения, например, модели и сервисы.
- infrastructure — технические детали, база данных, репозитории, обработка текста, логи и настройки. 

Вчера я не стал создавать все папки, потому что я не был уверен, насколько это необходимо для ктора, но сейчас понимаю, что в таком виде всё выглядит облезлым и малопонятным. (#_<-)

Сервисы не совсем domain  (хотя это может быть какие-то филологические придирки), потому что к бизнес–логике относятся и сами модели, которые нельзя отнести к другим слоям. Я добавил туда ещё и интерфейс репы, но только потому что такое деление я увидел в каком-то другом проекте, мне лично это не очень нравится.

Имплементацию репы я перенёс в инфраструктуру, т.к. к бизнес-логике это не относится точно. 

Config можно и перенести, но я не уверен, т.к. Monitoring, Serialization — это точно инфраструктура.

2024-10-01 10:58 UTC, LeonovDS commented
Распишу свою картинку мира, чтобы синхронизировать наши взгляды. Воспринимать не как наезд, а как мнение

Не знаю насчёт филологии, но в большинстве схем трёхслойной архитектуры эти два понятия соответствуют одному и тому же слою)

Модели в целом не являются частью бизнес-логики. В них нет содержательного кода. Они просто хранят данные. В особо запущенных случаях модели расползаются по всем трём слоям и в каждом из них есть своя папка model:
- Table или Dao в data/persistence/repository слое для взаимодействия с БД
- Модели для бизнес-логики в domain/service слое для взаимодействия с data и presentation слоем
- Модели для request/response в presentation/web слое для взаимодействия с клиентом

Инфраструктура в моём понимании - это вообще Gradle, Docker, ci и подобные вещи. Плюс-минус все, что там есть сейчас - именно конфигурация самого сервера, а не его окружения. Поэтому и предлагаю config, но это вкусовщина

Имплементация интерфейса на данном этапе проекта (пока нет сложной многомодульности) должна быть неподалёку от самого интерфейса, так как у них общий смысл. Мы можем даже без них обойтись, так как не будем писать тесты, а значит ничего не будем мокать. Но ради приличия лучше сделать

2024-10-01 11:35 UTC, witbore commented
Дело в том, что я разделяю тут домен (всё, что относится к бизнес-логике) и сервисы (реализация логики). В таком случае модель односится к домену, т.к. несмотря на отсутсвие кода, их реализация определяется требованиями логики приложения. В таком случае выделение моделей для каждого слоя мне представляется наиболее симпатичным. Как бы то ни было, у меня нет большого обыта разработки архитектуры приложения, так что [тут решай](https://shadowzael.wordpress.com/wp-content/uploads/2015/10/commie-owarimonogatari-01-00b15f61-mkv_snapshot_14-49_2015-10-10_20-26-20.jpg) ты.

Инфраструктура у меня всё, что не относится напрямую к логике решения задачи, а лишь предоставляет среду для её выполнения. Поэтому репы и конфиг там.

Про интерфейсы понял-принял.

2024-10-08 10:12 UTC, LeonovDS approved these changes

2024-10-08 10:12 UTC, merged