Create schema for text fragments rebased from main
TangutCorpus/TangutSite pull request #52
Opened 2024-10-22 11:40 UTC by witbore

After merging the #47 with main, I decided to rebase the #48 on the top of it, because of the shared code (namely, ErrorHandling configuration). I force pushed it, but the GitHub automatically closed the PR and now I am unable to create a new request from that branch, so created this.

Basically, it closes #25.

2024-10-27 16:11 UTC, LeonovDS requested changes
По большей части ок, смотри придирки к data class-у

2024-10-27 16:12 UTC, LeonovDS commented on backend/src/main/kotlin/com/example/model/TextFragment.kt
> + * @property content Actual XML representation of the fragment.
Если хранится xml - лучше добавить это в название переменной

2024-10-27 16:13 UTC, LeonovDS commented on backend/src/main/kotlin/com/example/model/TextFragment.kt
> + * @property createdAt? The time of the table creation/
Для этого есть DateTime тип (либо из java, либо из kotlinx.datetime)

2024-10-29 08:15 UTC, LeonovDS commented on backend/src/main/kotlin/com/example/repository/TextFragmentRepositoryImpl.kt
> +            it[createdAt] = textFragment.createdAt?.let { it -> LocalDateTime.parse(it.toString()) }
ИМХО, преобразование в LocalDateTIme должно произойти в сервисе (раз уж там происходит валидация других полей). А то тут выходит, что если происходит какая-то ошибка, то мы получим null, но не объяснение, в чем проблема

2024-10-29 10:49 UTC, witbore commented
Я не уверен, что имеет смысл создавать отдельный объект для двух уровней запросов на данном этапе, поскольку у такого подхода нет больших преимуществ, а классов поддерживать придётся больше. Если есть другие мысли, то открыт к дискуссии.

2024-10-30 17:39 UTC, LeonovDS requested changes
Ок, пусть пока будет так

2024-10-30 17:39 UTC, LeonovDS approved these changes

2024-10-30 17:40 UTC, merged